---
- name: run mysqld_safe
  shell: mysqld_safe > /dev/null 2>&1 &
         sleep 5

- name: Get mariadb version.
  command: 'mysql --version'
  register: mariadb_cli_version
  changed_when: false

- name: Disallow root login remotely
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Get list of hosts for the root user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  register: mariadb_root_hosts
  changed_when: false
  # check_mode: no

- name: Set root Password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
    state: present
  with_items: "{{ mariadb_root_hosts.stdout_lines | default([]) }}"

# Has to be after the root password assignment, for idempotency.
- name: Copy .my.cnf file with root password credentials.
  template:
    src: user-my.cnf.j2
    dest: "{{ mariadb_user_home }}/.my.cnf"
    mode: 0600

- name: Get list of hosts for the anonymous user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mariadb_anonymous_hosts
  changed_when: false
  # check_mode: no

- name: Remove anonymous mariadb users.
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items: "{{ mariadb_anonymous_hosts.stdout_lines | default([]) }}"

- name: Remove mariadb test database.
  mysql_db:
    name: test
    state: absent
