---
# variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# install
- name: Add mariadb repository.
  yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: http://yum.mariadb.org/{{ mariadb_version }}/centos7-amd64
    gpgcheck: no
    enabled: no

- name: Ensure mariadb packages are installed.
  yum: name={{ item }} state=latest enablerepo={{ mariadb_enablerepo }}
  with_items: "{{ mariadb_packages | default([]) }}"
  notify: restart mariadb

# configure
- name: Copy mariadb configuration file in place.
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mariadb

- name: Create log dir if it does not exist
  file:
    path: "{{ mariadb_log_dir }}"
    owner: mysql
    group: mysql
    state: directory

- name: Touch slow query log file.
  copy:
    dest: "{{ mariadb_slow_query_log_file }}"
    content: ""
    owner: mysql
    group: mysql
    mode: 0640
    force: no

- name: Touch error log file.
  copy:
    dest: "{{ mariadb_log_error }}"
    content: ""
    owner: mysql
    group: mysql
    mode: 0640
    force: no

# service
- name: Ensure mariadb is started and enabled to start at boot.
  service: name=mariadb state=started enabled=yes
  when: ansible_connection != 'docker'

# secure installation
- include: init_db.yml
  when: ansible_connection != 'docker'

# docker tasks
- name: Clean the repository
  shell: yum -y update && \
         yum clean all
  when: ansible_connection == 'docker'
